train_uri: 
  - [
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/103_WardsButteSx/Data/ortho/03WardsButteSxGR02122023_Orthomosaic_WedMar08194203915827/03WardsButteSxGR02122023_Orthomosaic_export_WedMar08194203915827.tif",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/104_FinalSalem/Data/ortho/04FinalSalemGR02122023_Orthomosaic_WedMar08195655345878/04FinalSalemGR02122023_Orthomosaic_export_WedMar08195655345878.tif",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/105_WinStormGTF/Data/ortho/05WinstormGR02122023_Orthomosaic_WedMar08201410773708/05WinstormGR02122023_Orthomosaic_export_WedMar08201410773708.tif",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/108_Moffit/Data/ortho/08MoffitGR02122023_Orthomosaic_export_FriMar10183649417525.tif"
  ]
  # - [
  #   "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/Tree_polygons_00_230OG.geojson",
  #   "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/103_WardsButteSx/Training/WardsButte_trees_poly.geojson",
  #   "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/104_FinalSalem/Training/FinalSalem_tree_polys.geojson",
  #   "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/105_WinStormGTF/Training/Tree_poly.geojson",
  #   "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/108_Moffit/Training/Trees.geojson"

  # ]
  - "/home/aerotract/NAS/main/JackSandbox/merged-giustina.geojson"
  - [
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/103_WardsButteSx/Training/WardsButte_sample_boundary.geojson",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/104_FinalSalem/Training/finalSalem_sample_Boundary.geojson",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/105_WinStormGTF/Training/Sample_Boundary.geojson",
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/108_Moffit/Training/Boundary.geojson"
  ]

val_uri: 
  - [
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif"
  ]
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/Tree_polygons_00_230OG.geojson"
  - [
    "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson"
  ]

pred_uri: 
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Data/ortho/Tiled/230OG_Orthomosaic"


output:
  uri: "/home/aerotract/NAS/main/JackSandbox/objdet/finally-working"

class_config:
  names: ["null", "DF"]
  colors: ["black", "orange"]

train_data_kw:
  size_lims: [300,500]
  out_size: 325
  max_windows: 5000
  batch_size: 2

val_data_kw:
  size: 325
  stride: 325

pred_data_kw:
  size: 325
  stride: 325

model_kw:
  name: fasterrcnn_resnet50_fpn_v2
  lr: 1e-4
  
train_kw:
    epochs: 50

predict_kw: 
  max_images: -1
