train_uri: 
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif"
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/Tree_polygons_00_230OG.geojson"
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson"

val_uri: 
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif"
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/Tree_polygons_00_230OG.geojson"
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson"

pred_uri: 
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Data/ortho/Tiled/230OG_Orthomosaic"
  - "/home/aerotract/NAS/main/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson"

output:
  uri: "home/aerotract/NAS/main/JackSandbox/longer-train-output"

class_config:
  names: ["DF", "null"]
  colors: ["orange", "black"]

train_ds_kw:
  size_lims: [300,500]
  out_size: 325
  max_windows: 100

val_ds_kw:
  size: 325
  stride: 325

pred_ds_kw:
  size: 325
  stride: 325
  num_images: 10

train_kw:
  batch_size: 8
  lr: 1e-4
  epochs: 50

predict_kw: 
  num_preds: 10
  polygon_output: True
  denoise: 10
  polygon_classes: [0]